// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvfveigdyhwzhnywhxbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2ZnZlaWdkeWh3emhueXdoeGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzE3OTksImV4cCI6MjA2MTI0Nzc5OX0.tOmqhWx5jNvfyMgjA5Su-R2-01II8TPvARH2IWHV6ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);