// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsvillwhqudbtsiaoqfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdmlsbHdocXVkYnRzaWFvcWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjM2OTMsImV4cCI6MjA2NTE5OTY5M30.FepuUp4MU_Lf9kj9O2y_eXYtJ2R_fXbwJHjB6M4Xo6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);